# Generated by Django 3.2.6 on 2021-08-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glitchassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hwNumber', models.IntegerField()),
                ('url', models.URLField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.student')),
            ],
        ),
    ]
