# Generated by Django 3.2.6 on 2022-02-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_glitchassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresetChallenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.TimeField()),
                ('event_end', models.TimeField()),
                ('player_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameChallenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.IntegerField()),
                ('lockernumber', models.IntegerField()),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('logged_in', models.BooleanField()),
                ('time_started', models.TimeField()),
                ('latest_time', models.TimeField()),
                ('PresetChallenger', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='frontend.presetchallenger')),
            ],
        ),
    ]
