# Generated by Django 3.2.6 on 2022-02-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_gamechallenger_presetchallenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamechallenger',
            name='latest_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gamechallenger',
            name='logged_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamechallenger',
            name='time_started',
            field=models.TimeField(null=True),
        ),
    ]
