# Generated by Django 3.2.6 on 2022-02-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20220211_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamechallenger',
            name='PresetChallenger',
        ),
        migrations.AddField(
            model_name='presetchallenger',
            name='GameChallenger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.gamechallenger'),
        ),
    ]
