# Generated by Django 3.2.6 on 2022-02-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20220211_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetchallenger',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
