# Generated by Django 3.2.6 on 2022-02-11 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_presetchallenger_gamechallenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presetchallenger',
            name='GameChallenger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.gamechallenger'),
        ),
    ]
