# Generated by Django 3.2.6 on 2022-02-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_presetchallenger_gamechallenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamechallenger',
            name='latest_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamechallenger',
            name='time_started',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
